# Generated by Django 6.0.3 on 2026-03-27 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0002_alter_customuser_user_type_downloadlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'nsuser')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='downloadlog',
            name='downloaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
