# Generated by Django 6.0.3 on 2026-03-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0003_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'nsuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
