# Generated by Django 6.0.3 on 2026-03-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0004_visitorlog_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'nsuser')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='notes_files'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='notes_files'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='notes_files'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='notes_files'),
        ),
    ]
