# Generated by Django 6.0.3 on 2026-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0005_alter_customuser_user_type_alter_notes_file1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'nsuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
